### PR TITLE
Remove a buggy type conversion in decoder

### PR DESCRIPTION
**Pull request by yqszxx**
Remove a meaningless `toInt` type conversion in `QMCDecoder` which causes a limitation of 32 on the number of output values.

### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [x] Did you add at least one test demonstrating the PR?
- [ ] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [ ] Did you add appropriate documentation in `docs/src`?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

- bug fix

#### API Impact
None.

#### Backend Code Generation Impact
None.

#### Desired Merge Strategy

- Squash: The PR will be squashed and merged (choose this if you have no preference.

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (3.2.x, 3.3.x, 3.4.0, 3.5.0) ?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

**Comment by edwardcwang** [comment]
No unit test?

**Comment by sequencer** [comment]
LGTM, will merge to decoder branch after a test which can illustrate this issue.

**Comment by yqszxx** [comment]
Unit test added.

**Review by edwardcwang — APPROVED** [review]
Seems fine except that it needs a new re-basing.

**Comment by sequencer** [comment]
test under decoder branch:
```
git checkout decoder
```
use
```
git cherry-pick 83ffc670
sbt "testOnly chiselTests.util.experimental.decoder.QMCDecoderSpec"
```
got failed result, prove original implementation do have this issue:
```
[info] - should be simplified correctly *** FAILED ***
[info]   ChiselRunners.this.runTester(t, additionalVResources, annotations) was false (ChiselSpec.scala:39)
[info] ScalaTest
[info] Run completed in 7 seconds, 730 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed: Total 1, Failed 1, Errors 0, Passed 0
[error] Failed tests:
[error]         chiselTests.util.experimental.decoder.QMCDecoderSpec
[error] (Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
```
After applying fix patch
```
git cherry-pick 5d989c45
sbt "testOnly chiselTests.util.experimental.decoder.QMCDecoderSpec"
```
test success, prove this bug has been fixed.
```
[info] - should be simplified correctly
[info] ScalaTest
[info] Run completed in 7 seconds, 457 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Passed: Total 1, Failed 0, Errors 0, Passed 1
```
Good job @yqszxx !

**Comment by sequencer** [comment]
You can apply same patch to rocket-chip to fix the potential issue.

**Pull request merged**
