### PR TITLE
refactor github action

### PR DESCRIPTION
**Pull request by sequencer**
This PR refactor CI container out of GitHub Action to reduce docker maintenance effort.
Borrow Verilator CI by @ekiwi from chiseltest

### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [ ] Did you add at least one test demonstrating the PR?
- [ ] Did you delete any extraneous printlns/debugging code?
- [ ] Did you specify the type of improvement?
- [ ] Did you add appropriate documentation in `docs/src`?
- [ ] Did you state the API impact?
- [ ] Did you specify the code generation impact?
- [ ] Did you request a desired merge strategy?
- [ ] Did you add text to be included in the Release Notes for this change?

#### API Impact

None

#### Backend Code Generation Impact

None

#### Desired Merge Strategy
- Rebase: You will rebase the PR onto master and it will be merged with a merge commit.

#### Release Notes
None

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (3.2.x, 3.3.x, 3.4.x, 3.5.0) ?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

**Comment by ekiwi** [comment]
Compiling `verilator` + `espresso` seems fine to me. However, `z3` should just be installed as a standard package since we aren't really depending on any of its modern features and essentially any version from the last 5 years should work.

**Comment by ekiwi** [comment]
We could also just use the `verilator` package from the Ubuntu repository as long as we make sure to use at least the `20.04 LTS` version.

**Comment by sequencer** [comment]
> Compiling verilator + espresso seems fine to me. However, z3 should just be installed as a standard package since we aren't really depending on any of its modern features and essentially any version from the last 5 years should work.
We could also just use the verilator package from the Ubuntu repository as long as we make sure to use at least the 20.04 LTS version.

@ekiwi 
I think compiling from source provides a better flexibility to upgrade and test in some specific version. We can add more Verilator version to test the compatibility, it's unreasonable to limit users to a specific Verilator version.  
CI only runs long when changing version, so I think there won't exist any overhead here.

**Comment by sequencer** [comment]
WTF...
I totally don't know what hell with GitHub Action.

**Comment by sequencer** [comment]
Seems missing 
/home/runner/.cache/coursier/v1/https/oss.sonatype.org/content/repositories/snapshots/edu/berkeley/cs/firrtl_2.13/1.5-SNAPSHOT/firrtl_2.13-1.5-SNAPSHOT.jar
in class path for `noPluginTest`

**Comment by sequencer** [comment]
Ready for review.

**Review by jackkoenig — APPROVED** [review]

**Comment by jackkoenig** [comment]
I see this is marked rebase, please rebase and then merge!

**Pull request merged**
