### PR TITLE
Fix higher-kinded types for autoclonetype

### PR DESCRIPTION
**Pull request by azidar**
Fixes https://github.com/chipsalliance/chisel3/issues/1893

### Contributor Checklist

- [N/A] Did you add Scaladoc to every public function/method?
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [N/A] Did you add appropriate documentation in `docs/src`?
- [x] Did you state the API impact?
- [N/A] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?
- [N/A] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

  - bug fix

#### API Impact

Makes autoclonetype work in all cases (that we know of). We expect this change should enable us to require the compiler plugins.

#### Desired Merge Strategy

 - Squash: The PR will be squashed and merged (choose this if you have no preference.

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (Bug fix: `3.3.x`, [small] API extension: `3.4.x`, API modification or big change: `3.5.0`)?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

**Review by mwachs5 — COMMENTED** [review]
Ah, so you fixed the bug vs making it a "go implement `cloneType` for your higher kinded type thing" error message?

**Comment by mwachs5** [comment]
Fixes #1893 ?

**Comment by jackkoenig** [comment]
> Fixes #1893 ?

Yep!

**Review by jackkoenig — APPROVED** [review]
LGTM, nice!

**Pull request merged**
