### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Burnleydev1**
### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [ ] Did you add at least one test demonstrating the PR?
- [ ] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [ ] Did you add appropriate documentation in `docs/src`?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement
Documentation

#### API Impact
No impact

#### Backend Code Generation Impact
No impact

#### Desired Merge Strategy
Squash

#### Release Notes
update CONTRIBUTING.md

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [x] Did you mark the proper milestone (Bug fix: `3.3.x`, [small] API extension: `3.4.x`, API modification or big change: `3.5.0`)?
- [x] Did you review?
- [x] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

**Comment by mwachs5** [comment]
looks good! I didn't add a backport since I'm not sure it's that useful on the backport branches

**Comment by Burnleydev1** [comment]
> well, since the changes are mostly to the README and other documents people see when they visit GitHub, that is not true. I am assuming people would look at the default branch on github, which is the `master` branch, and that will be visible as soon as this merges. These changes won't impact anything on the website.
> 
> If someone wanted to read the README on the 3.4.x branch (like this: https://github.com/chipsalliance/chisel3/tree/3.4.x) then they wouldn't see your changes, but that seems like an unlikely use case

Okay, that means whether changes are backported or not, they will still be visible on github.

**Comment by mwachs5** [comment]
Correct

**Comment by Burnleydev1** [comment]
> well, since the changes are mostly to the README and other documents people see when they visit GitHub, that is not true. I am assuming people would look at the default branch on github, which is the `master` branch, and that will be visible as soon as this merges. These changes won't impact anything on the website.
> 
> If someone wanted to read the README on the 3.4.x branch (like this: https://github.com/chipsalliance/chisel3/tree/3.4.x) then they wouldn't see your changes, but that seems like an unlikely use case.
> 
> This makes me realize maybe we should add this information to CONTRIBUTING guide:
> 
> "Please make your PRs against `master` branch. The reviewers will take care to make sure the backports to the necessary stable branches happen".
> 
> We can also document our backport policy. But, I think none of that needs to block this PR, we can always enhance this guide now you have written it!

I completely missed that point, I thought you were telling me to make it against the master branch rather.
can I begin documenting on the backport policy?

**Comment by mwachs5** [comment]
> I thought you were telling me to make it against the master branch rather.


Yes, you should almost always make your PRs against the `master` branch.

> can I begin documenting on the backport policy?

I *think* this is already documented somewhere. What do you mean exactly by the policy? This is already in the PR template:  `Did you mark the proper milestone (Bug fix: 3.3.x, [small] API extension: 3.4.x, API modification or big change: 3.5.0)?`

One key concept is that the release branches must stay binary compatible (https://docs.scala-lang.org/overviews/core/binary-compatibility-of-scala-releases.html#:~:text=When%20two%20versions%20of%20Scala,run%2Dtime%20linkage%20(only!)&text=We%20check%20binary%20compatibility%20automatically%20with%20MiMa.)

**Comment by Burnleydev1** [comment]
> I _think_ this is already documented somewhere. What do you mean exactly by the policy? This is already in the PR template: `Did you mark the proper milestone (Bug fix: 3.3.x, [small] API extension: 3.4.x, API modification or big change: 3.5.0)?`
> 
> One key concept is that the release branches must stay binary compatible (https://docs.scala-lang.org/overviews/core/binary-compatibility-of-scala-releases.html#:~:text=When%20two%20versions%20of%20Scala,run%2Dtime%20linkage%20(only!)&text=We%20check%20binary%20compatibility%20automatically%20with%20MiMa.)


I'm saying so because you mentioned the need to document our backport policy in the CONTRIBUTING.md file.

> We can also document our backport policy. But, I think none of that needs to block this PR, we can always enhance this guide now you have written it!

**Pull request merged**
