### PR TITLE
readme: simplify sbt snippet and update to the latest stable release

### PR DESCRIPTION
**Pull request by ekiwi**
### Contributor Checklist

- [x] Did you specify the type of improvement?

#### Type of Improvement

- documentation improvement

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (3.2.x, 3.3.x, 3.4.0, 3.5.0) ?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

**Review by jackkoenig — APPROVED** [review]
LGTM, thanks!

Backporting to `3.4.x` because that's what's used on the website (and this README is still the landing page)

**Comment by ekiwi** [comment]
> LGTM, thanks!

did you double check that I did not break anything?

Also, is it ok, that I made "chiseltest" a test dependency only?

**Comment by jackkoenig** [comment]
> did you double check that I did not break anything?

Not originally, but just did and it works. These instructions are too minimal IMO, but your change was just updating the versions and artifacts which you did correctly 🙂 

> Also, is it ok, that I made "chiseltest" a test dependency only?

Not only is it "okay", I think it is better and should be what we encourage.

**Comment by ekiwi** [comment]
> These instructions are too minimal IMO

Also somewhat passive aggressive:
> If you insist on setting up your own project

**Comment by jackkoenig** [comment]
Yeah, we really need to just improve chisel-template, make it a proper Github template and also post tarballs and maybe fat tarballs (that include all dependencies).

**Pull request merged**
