### PR TITLE
Change SInt unary negation (expanding width) note

### PR DESCRIPTION
**Pull request by moriglia**
Fix chipsalliance/chisel3#2728

### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
  No function/method added
- [ ] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [ ] Did you add appropriate documentation in `docs/src`?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?
- [ ] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

- documentation

#### API Impact

No API impact

#### Backend Code Generation Impact

No backend code generation impact

#### Desired Merge Strategy

- Squash: The PR will be squashed and merged (choose this if you have no preference.

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (Bug fix: `3.4.x`, [small] API extension: `3.5.x`, API modification or big change: `3.6.0`)?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you do one of the following when ready to merge:
  - [ ] Squash: You/ the contributor `Enable auto-merge (squash)`, clean up the commit message, and label with `Please Merge`.
  - [ ] Merge: Ensure that contributor has cleaned up their commit history, then merge with `Create a merge commit`.

### CODE REVIEW

**Comment by aswaterman** [comment]
Isn't it the other way around: the comment three lines earlier is incorrect, whereas the one you changed was already correct?  I see that `unary_-` is defined to be `0.S - this`, and `-` is not expanding.

**Comment by jackkoenig** [comment]
I think actually both `unary_-` and `unary_-%` are non-expanding, see Scastie: https://scastie.scala-lang.org/NLnK5LqGSeKJOHSdqoY1HQ

Furthermore, `unary_-%` isn't a real unary operator (you can only call it as `mySInt.unary_-%`, see the [Scala language spec](https://scala-lang.org/files/archive/spec/2.12/06-expressions.html#prefix-operations).

**Comment by moriglia** [comment]
> Isn't it the other way around: the comment three lines earlier is incorrect, whereas the one you changed was already correct? I see that `unary_-` is defined to be `0.S - this`, and `-` is not expanding.
I see. However in the [documentation note](https://www.chisel-lang.org/api/latest/chisel3/SInt.html#-(that:T):T): "The width of the returned hardware type is max(width of this, width of that) + 1." Should this be also fixed?

What I found confusing is that for the "normal" subtraction we have
- Subtraction with no "&" or "%" is non-expanding, but its [note](https://www.chisel-lang.org/api/latest/chisel3/SInt.html#-(that:T):T) says that the size increases by 1
- Subtraction with "&" is expanding too ([note](https://www.chisel-lang.org/api/latest/chisel3/SInt.html#-&(that:chisel3.SInt):chisel3.SInt))
- Subtraction with "%" is non-expanding ([note](https://www.chisel-lang.org/api/latest/chisel3/SInt.html#-%(that:chisel3.SInt):chisel3.SInt))

So what I expected was a similar behaviour for the unary negation, i.e.:
- `unary_-`  expanding
- `unary_-%` non expanding

I've just noticed that there's no expanding width unary negation

> I think actually both `unary_-` and `unary_-%` are non-expanding, see Scastie: https://scastie.scala-lang.org/NLnK5LqGSeKJOHSdqoY1HQ

Thank you for the example. Doesn't it just show that I can represent both the expanding and the non-expanding results in +1 bits?
Anyway, I [modified the example](https://scastie.scala-lang.org/0DCnMhVWQlqMiZpmbVEEAw) and convinced myself that both of you are right

> Furthermore, `unary_-%` isn't a real unary operator (you can only call it as `mySInt.unary_-%`, see the [Scala language spec](https://scala-lang.org/files/archive/spec/2.12/06-expressions.html#prefix-operations).
Ok, true, I realized that because I had to use it in one of my modules an I had to use the postfix notation. Since I now realize that the `unary_-` is non-expanding, I'll put it back.

Shall I fix my commit and also change the note in the documentation for the normal subtraction?

Thanks for taking time to check into such a tiny and meaningless commit :)

**Comment by aswaterman** [comment]
Not a meaningless commit; it’s good to get this stuff correct :) we should change any incorrect documentation and keep the behavior as currently implemented to avoid creating any backwards incompatibility.

**Review by jackkoenig — APPROVED** [review]
Thanks for fixing the documentation!

**Comment by moriglia** [comment]
> Shall I fix my commit and also change the note in the documentation for the normal subtraction?

In the end I didn't touch the description for the normal subtraction. Is it somehow inherited from the Num trait?

**Pull request merged**
