### PR TITLE
Generate a balanced tree with reduceTree

### PR DESCRIPTION
**Pull request by schoeberl**
### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [ ] Did you add appropriate documentation in `docs/src`?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?
- [ ] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

- additional test

#### API Impact

non

#### Backend Code Generation Impact

non

#### Desired Merge Strategy

 - Squash: The PR will be squashed and merged (choose this if you have no preference.

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (Bug fix: `3.3.x`, [small] API extension: `3.4.x`, API modification or big change: `3.5.0`)?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

**Comment by schoeberl** [comment]
Shall I also move the other two ```reduceTree''' tests into this ```Spec'''?

Shall I include the fix for the unbalanced issue #2144 in this PR or in a different one?

**Comment by schoeberl** [comment]
fixes  #2144

Ready for review, Maybe @seldridge. However, I am missing the right to request a reviewer.

**Comment by sequencer** [comment]
I think there are two issues here:
1. if element of vector is not associative, this implementation will change the behavior.
2. implementation implemented a binary tree, which might be sub-optimized in ASIC designs.

**Comment by schoeberl** [comment]
Hi @sequencer, thanks for the review. However, I do not really understand your two questions. (1) what do you mean of vector associative and (2) I think a binary tree is the best solution we can do. The original implementation did something along this but unbalanced.

**Comment by sequencer** [comment]
Sorry for the delay response, my main concern here is:
1. the behavior of `reduceTree` is changed, that's my main concern, basically if the operation in `reduceTree` is not "associative": for example `+` operation to a IEEE754 floating data structure, this will break the legacy code.
If we need to make this change: we must have the deprecation flow.
2. For digital circuit designs: binary tree might not be the best solution, since high-fanout optimization can be leveraged to generate high density circuits, for example `OR4` use 10 transistors, while binary tree with 3*`OR2` use 18 transistors. Although this is the optimization what synthesis tools should take care of, I think arbitrary tree support to `reduceTree` might be a better solution.

So from my point of view, I think: behavior of the `reduceTree` should not be changed silently, since this might introduce bugs to users.
If we really want have a binary reduce tree support in `reduceTree`: I think we need to add another option to make this configureable, and use the current implementation by default to avoid subtle bug to users.

**Comment by jackkoenig** [comment]
I wanted to visualize the change here so I sketched up some code to generate a dotfile while running the reduction:
```scala
import chisel3._

import java.io._
import scala.collection.mutable

class TreeReduce extends Module {
  var i = 0L
  val map = new mutable.HashMap[Data, String]()
  val getName: Data => String = (d: Data) =>
    map.getOrElseUpdate(d, {
      val name = s"_T_$i"
      i += 1
      name
    })
  val in = IO(Input(Vec(5, UInt(8.W))))
  val out = IO(Output(UInt()))

  // Prepopulate names
  in.zipWithIndex.foreach { case (d, i) => map(d) = s"""\"in[$i]\"""" }

  val fw = new FileWriter(new File("output.dot"))
  fw.write("digraph g {\nnode [shape=plaintext];\n\n")

  out := in.reduceTree { (x, y) =>
    val res = x +% y
    fw.write(s"${getName(x)} -> ${getName(res)};\n")
    fw.write(s"${getName(y)} -> ${getName(res)};\n")
    res
  }
  fw.write("}\n")
  fw.close()
}
object Main extends App {
  println(getVerilogString(new TreeReduce))
}
```

### .reduce

reduce_5

### .reduceTree on master

reduceTree_5

### .reduceTree on this PR

**Note** that `in[0]` is no longer in the top-left, sorry about that. I didn't feel like figuring out how to make GraphViz do what I wanted here.

reduceTreeNew_5

**Comment by schoeberl** [comment]
Thank you for this drawing, I should have done it ;-) Yes, this is correct. And in my opinion, the current version is unfair, as in[4] has only one hop, while the others have three hops). The PR version resolves any difference at the first reduce step towards a power of 2 number of elements. At a power of 2, it is a perfect tree then.

Can we at some point merge this?

**Comment by jackkoenig** [comment]
Yeah I think we should merge this, I was trying to think of how to express the metric of "fairness" that makes this PR better than the current implementation and I think it's enough to just say that it reduces both the mean and standard deviation of the levels of logic each value goes through:

  | reduce | master | this PR
-- | -- | -- | --
  | 4 | 3 | 3
  | 4 | 3 | 3
  | 3 | 3 | 2
  | 2 | 3 | 2
  | 1 | 1 | 2
**Mean** | 2.8 | 2.6 | 2.4
**SD** | 1.3 | 0.9 | 0.5

**Review by jackkoenig — APPROVED** [review]

**Comment by schoeberl** [comment]
About the fairness: with this PR the difference between paths is a maximum of 1, independent of the size. In the current version, the difference grows with the size of the Vec.

BTW, I cannot merge. I have no write access.

**Comment by jackkoenig** [comment]
I've resolved the conflicts, run ScalaFmt, and fixed a minor inconsistency in code generation between Scala 2.12 and 2.13 (that I noticed elsewhere but figured we might as well fix while touching this code).

**Comment by schoeberl** [comment]
Interesting little detail. Thanks.

**Pull request merged**
