### PR TITLE
Removed Flush references for the 3.4.x branch

### PR DESCRIPTION
**Pull request by Burnleydev1**
### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [ ] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [x] Did you add appropriate documentation in `docs/src`?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release Notes for this change?

#### API Impact
Unknown

#### Backend Code Generation Impact
Unknown

#### Desired Merge Strategy
Squash

#### Release Notes
Removed Flush references for the 3.4.x branch

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (Bug fix: `3.3.x`, [small] API extension: `3.4.x`, API modification or big change: `3.5.0`)?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

**Comment by Burnleydev1** [comment]
Hi @mwachs5, please my machine will soon go off and there was a blackout here, I will come and do more analysis error later.
But I have removed Flush references and I still got the sane error the mergify backport PR returned.

**Comment by mwachs5** [comment]
Ok, the issue here is that you are working off the wrong branch and trying to merge into master. For the backport, you should start with the automatically created branch: https://github.com/chipsalliance/chisel3/pull/2231, the branch is  `mergify/bp/3.4.x/pr-2214`.

So in your local checkout you'd do:
```
git fetch origin // assuming this is chipsalliance/chisel3
git checkout origin/mergify/bp/3.4.x/pr-2214`
git checkout -b mergify/bp/3.4.x/pr-2214
// resolve the merge conflicts
git push Burnleydev1/mergify/bp/3.4.x/pr-2214
```
Then make a PR from your repo to the chipsalliance repo, and make sure the target branch is  `mergify/bp/3.4.x/pr-2214`, not `master`.

That will have the effect of cleaning up the backport PR vs creating a new one, which is what we want.

You may also be able to use the GitHub UI to resolve the conflicts and open the PR as described as they are pretty simple.

**Review by mwachs5 — CHANGES_REQUESTED** [review]
Let's clean up the backport in #2231 instead of creating a new PR

**Comment by Burnleydev1** [comment]
Thanks a lot for the clarification, I did a commit removing the flush references, Thanks again.

**Comment by mwachs5** [comment]
> Thanks a lot for the clarification, I did a commit removing the flush references, Thanks again.

No, this is still not right. You can see that I changed the base branch to be `chipsalliance:mergify/bp/3.4.x/pr-2214` and this is showing hundreds of files changed. You need to *start* your fixup PR from `chipsalliance:mergify/bp/3.4.x/pr-2214`, not from your original PR's branch.

(This is why having the mergify tool do this for us is so nice!)

**Comment by Burnleydev1** [comment]
Hi @mwachs5, I used the method from terminal and I was told I never had the correct access rights
```
abongwa@abongwa-UX430UAR  ~/Desktop/new contribution/backport/chisel3   mergify/bp/3.4.x/pr-2214 ±  git push Burnleydev1/mergify/bp/3.4.x/pr-2214
fatal: 'Burnleydev1/mergify/bp/3.4.x/pr-2214' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Burnleydev1** [comment]
> Hi @mwachs5, I used the method from terminal and I was told I never had the correct access rights
> 
> ```
> abongwa@abongwa-UX430UAR  ~/Desktop/new contribution/backport/chisel3   mergify/bp/3.4.x/pr-2214 ±  git push Burnleydev1/mergify/bp/3.4.x/pr-2214
> fatal: 'Burnleydev1/mergify/bp/3.4.x/pr-2214' does not appear to be a git repository
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> ```

Screenshot from 2021-11-03 17-08-59

**Comment by Burnleydev1** [comment]
> Ok, the issue here is that you are working off the wrong branch and trying to merge into master. For the backport, you should start with the automatically created branch: #2231, the branch is `mergify/bp/3.4.x/pr-2214`.
> 
> You may be able to use the GitHub UI to resolve the conflicts on #2231.
> 
> If the GitHub UI doesn't work, in your local checkout you'd do:
> 
> ```
> git fetch origin // assuming this is chipsalliance/chisel3
> git checkout origin/mergify/bp/3.4.x/pr-2214
> git checkout -b mergify/bp/3.4.x/pr-2214
> // resolve the merge conflicts
> git push Burnleydev1/mergify/bp/3.4.x/pr-2214
> ```
> 
> Then make a PR from your repo to the chipsalliance repo, and make sure the target branch is `mergify/bp/3.4.x/pr-2214`, not `master`.
> 
> That will have the effect of cleaning up the backport PR vs creating a new one, which is what we want.

after switching to the ```origin/mergify/bp/3.4.x/pr-2214```, I wish to know why I am switching to ```mergify/bp/3.4.x/pr-2214```.

**Comment by mwachs5** [comment]
sorry there was a bug in my `git push` command, there shoudl be a space:

```
git push Burnleydev1 mergify/bp/3.4.x/pr-2214
```

**Comment by mwachs5** [comment]
> after switching to the origin/mergify/bp/3.4.x/pr-2214, I wish to know why I am creating mergify/bp/3.4.x/pr-2214.

This is me being a bit verbose. You could just do:

```
git checkout mergify/bp/3.4.x/pr-2214
```
and it will automatically grab `origin/mergify/bp/3.4.x/pr-2214` and call it `mergify/bp/3.4.x/pr-2214`.

This only works if you don't also have a `Burnleydev1/mergify/bp/3.4.x/pr-2214`

(I am not quite sure what `origin` is for you, whether that is chipsalliance or Burnleydev1, depends on what you see when you do `git remote -v`)

**Comment by Burnleydev1** [comment]
Hi @mwachs5, I'm closing this as https://github.com/chipsalliance/chisel3/pull/2235 solved the issue.

**Comment by Burnleydev1** [comment]
Hi @mwachs5, I'm closing this as #2235 solved the issue.

**Pull request closed without merging**
