### PR TITLE
doc: link to developer style guide

### PR DESCRIPTION
**Pull request by schoeberl**
just a minor documentation fix

### CODE REVIEW

**Review by ekiwi — APPROVED** [review]

**Comment by schoeberl** [comment]
Someone else needs to do the merge, as I do not have write access to the chisel3 repo.

Maybe it would make stuff easier if someone grants me write access.

**Comment by ekiwi** [comment]
> Someone else needs to do the merge, as I do not have write access to the chisel3 repo.

I would merge this, I just do not know if this needs to be backported. Paging @jackkoenig

**Comment by schoeberl** [comment]
Is this tiny, tiny change worth all the procedure, e.g., about backporting?

**Comment by ekiwi** [comment]
> Is this tiny, tiny change worth all the procedure, e.g., about backporting?

If it was up to me I would not backport anything, but the SiFive folks care.

**Comment by jackkoenig** [comment]
Need to backport to latest stable (`3.4.x`) for things to show up on the website: https://www.chisel-lang.org/chisel3/docs/developers/developers.html

**Comment by jackkoenig** [comment]
Let the bots do their thing and this should be live tomorrow on the link above

**Pull request merged**
