### PR TITLE
Fix CI.

### PR DESCRIPTION
**Pull request by sequencer**
### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [ ] Did you add at least one test demonstrating the PR?
- [ ] Did you delete any extraneous printlns/debugging code?
- [ ] Did you specify the type of improvement?
- [ ] Did you add appropriate documentation in `docs/src`?
- [ ] Did you state the API impact?
- [ ] Did you specify the code generation impact?
- [ ] Did you request a desired merge strategy?
- [ ] Did you add text to be included in the Release Notes for this change?

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (3.2.x, 3.3.x, 3.4.x, 3.5.0) ?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

**Comment by sequencer** [comment]
CI is crazy??? cache hit but not found?

**Comment by sequencer** [comment]
> /usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/e5d0f4b8-6b6b-4b84-be5f-3ad4f17bc00e/cache.tzst -P -C /home/runner/work/chisel3/chisel3

Seems I need to checkout first.

**Comment by sequencer** [comment]
Not work

**Comment by sequencer** [comment]
> Run actions/cache@v2
  with:
    path: z3-z3-4.8.10
    key: Linux-z3-4.8.10
Received 22 of 22 (100.0%), 0.0 MBs/sec
Cache Size: ~0 MB (22 B)
/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/ef67345f-cdda-4b04-8dd3-019b482d98a9/cache.tzst -P -C /home/runner/work/chisel3/chisel3
Cache restored successfully
Cache restored from key: Linux-z3-4.8.10

WTF?

**Comment by sequencer** [comment]
CI issue introduced in https://github.com/chipsalliance/chisel3/runs/3050952870

**Review by seldridge — APPROVED** [review]

**Comment by sequencer** [comment]
Hopefully this affects nobody's work :(
My bad.

**Pull request merged**
