### PR TITLE
Move prefix and noprefix from internal to experimental

### PR DESCRIPTION
**Pull request by jackkoenig**
Previously, they were aliases into experimental but this does not work very well for ScalaDoc.

### Contributor Checklist

- [x] Did you add Scaladoc to every public function/method?
- [ ] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [x] Did you add appropriate documentation in `docs/src`?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

   - code refactoring

#### API Impact

This is a binary API breakage, but it is source compatible.

#### Backend Code Generation Impact

No impact

#### Desired Merge Strategy

 - Squash

#### Release Notes

Move implementation of `prefix` and `noprefix` from `chisel3.internal` to `chisel3.experimental`. They were previously aliased in experimental which does not work very well in the generated API docs.

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (Bug fix: `3.4.x`, [small] API extension: `3.5.x`, API modification or big change: `3.6.0`)?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you do one of the following when ready to merge:
  - [ ] Squash: You/ the contributor `Enable auto-merge (squash)`, clean up the commit message, and label with `Please Merge`.
  - [ ] Merge: Ensure that contributor has cleaned up their commit history, then merge with `Create a merge commit`.

### CODE REVIEW

**Comment by mwachs5** [comment]
I think there are some docs with this in the naming cookbook? Let's make sure they don't show the now-deprecated version

**Comment by jackkoenig** [comment]
> I think there are some docs with this in the naming cookbook? Let's make sure they don't show the now-deprecated version

The docs already import from `chisel3.experimental.prefix` because we were aliasing from there back to internal--now the alias is reversed.

This is failing CI because it is a binary incompatible change and thus the published chiseltest artifact does not work. We have the label to skip chiseltest CI but the problem is it will still fail on the push to master and thus new SNAPSHOTs will not be published. I could change this to not use an alias but rather use a deprecated object in package internal that has it's own apply method that just invokes the version in experimental. I'll do this tomorrow.

**Review by chick — APPROVED** [review]
lgtm

**Comment by jackkoenig** [comment]
I cannot figure out how to avoid the binary compatibility issue. Keeping around the old object doesn't seem to do it so I'm at a loss. I'll just stick with the deprecated alias and manually publish SNAPSHOTs to deal with the integration test crash.

**Comment by mwachs5** [comment]
I'm confused about the binary compatibility issue, doesn't that check only exist on backport branches?

**Pull request merged**
