### PR TITLE
Add API for setting MultiClock in current Module scope

### PR DESCRIPTION
**Pull request by colin4124**
### Contributor Checklist

- [x] Did you add Scaladoc to every public function/method?
- [ ] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [ ] Did you add appropriate documentation in `docs/src`?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [ ] Did you request a desired merge strategy?
- [ ] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

new feature/API

#### API Impact

Not affect existing API, it does much like `withClockAndReset` `withClock` `withReset`,  but set Clock/Reset in current Module scope.

Because `Module(new xxx_module)`, the `Module()` would set `Builder.currentClock` to `None`,  `setClock`  does not need to set `None` again.

#### Backend Code Generation Impact

Not Change.

#### Desired Merge Strategy

Squash

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (3.2.x, 3.3.x, 3.4.x, 3.5.0) ?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

**Comment by sequencer** [comment]
Why not directly connect clock and reset from the outsider module?
Wondering the real use cases.

**Comment by edwardcwang** [comment]
Also, missing unit tests

**Comment by colin4124** [comment]
@sequencer 

```scala
class Top extends RawModule {
  val myclk = Input(Clock())
  val myrst = Input(Bool())

  withClockAndReset(myclk, myrst) {
    val a =  RegInit(0.U)
    val b =  RegInit(0.U)
    // My Moudle Logic etc.
    ...
  }
}

I don't want to all my module logic code indent in `withClockAndReset` scope. I prefer this:

```scala
class Top extends RawModule {
  val myclk = Input(Clock())
  val myrst = Input(Bool())

  setClockAndReset(myclk, myrst)

  val a =  RegInit(0.U)
  val b =  RegInit(0.U)

  // My Moudle Logic etc.
  ...
}
```

It is not a necessary， it just for  convenience and  may be an alternative.

**Comment by edwardcwang** [comment]
If you want to write your synchronous logic without indents why not just stick them in a regular module and wrap instantiation in `withClockAndReset`? What I like about `withClockAndReset` is that the scope makes it very clear what is going on whereas a function call looks like it's manipulating magic state.

```scala
val a =  RegInit(0.U)
val b =  RegInit(0.U)
```

**Comment by colin4124** [comment]
@edwardcwang I think so `withClockAndReset { ... }` is more clear, and `setClockAndReset` have side effect.

I just give a one more option to user, and this API is very convenient and doesn't make any bad effect, it just syntactic sugar.

Such as some one would use:

```scala
my_list foreach { println(_) } 
```

and other one prefer:

```scala
my_list foreach println
```

**Comment by sequencer** [comment]
I personally think this has two edges:
the good one is, registers can be refered more easily, for example original with has this shortage:
```
val someWire = Wire(UInt(32.W))
withClock(clock2) {
  val a = RegInit(0.U(32.W)) // this reg cannot be refered other of withClock scope
  someWire := a // bind a to external wire, then we can read this wire.
  ... // other operations 
}
```
However, this API may introduce dangerous operations. For example, a very deep function calling this new API and forgot to release to original `clock` and `reset` may lead to a some potential problem, for example, sub-modules will be instantiated under this `clock` and `reset`, and you may not be able to find them. while original method provides a scope management for `clock` and `reset`, which helps user understanding which clock domain they are operating on.

**Comment by colin4124** [comment]
@sequencer 

When you call `Module(new a_sub_module)`, it would set current clock/reset scope to None, so sub-module not use its parent's clock and reset implicitly. 

Use `setClockAndReset` in `RawModule` If a module have only one clock domain, it is called in front of the module logic, and then write your code as you use `extends Module`.

**Review by jackkoenig — CHANGES_REQUESTED** [review]
I'm not okay with exposing mutation to the user like this. While the standard use-case of having a single clock and reset for a `RawModule` is reasonable, I don't think this is the way to accomplish it. We already have support for modules with a single clock and reset: `MultiIOModule` (becoming `Module` in Chisel 3.5).

I'm guessing the fundamental problem here is that you want to control the _name_ of the single clock and reset in a `MultiIOModule`, and I think we could accomplish this in a different way. For example, instead of making the implicit clock and reset in `MultiIOModule` special, we could add a trait for having the implicit clock and reset that provides virtual methods the user must implement, giving them control over the naming, something like:

```scala
trait ImplicitClockAndReset {
  def clock: Clock
  def reset: Reset
  // or
  def clockAndReset: (Clock, Reset)
}
class MyRawModule extends RawModule with ImplicitClockAndReset {
  val myclk = IO(Input(Clock()))
  val myrst = IO(Input(AsyncReset()))

  def clock = myclk
  def reset = myreset
  // Or
  def clockAndReset = (clock, reset)
  ...
}
```

Something like this should fulfill your desired functionality without the negative potential for users doing weird things like changing the clock and reset arbitrarily, or accidentally changing it in a function call that forgets to set it back.

**Comment by jackkoenig** [comment]
I'll note that there are potential consequences of initialization order here, so this idea may not work (if those defs get called too early, the vals won't yet have been initialized). Another things we could do is just expose the ability to _name_ `clock` and `reset` but keep the vals as `clock` and `reset`.

**Comment by colin4124** [comment]
@jackkoenig Yes, I  want to control the name of the single clock and reset.

Application scenarios: only one clock domain. Once it set, no need to set it back. `Module(..)` will take care of it.

Maybe abuse of setting clock but more flexible,  I understand what you concern.

**Pull request closed without merging**
