### PR TITLE
deprecate strongenum annos

### PR DESCRIPTION
**Pull request by sequencer**

### CODE REVIEW

**Comment by jackkoenig** [comment]
This is fine to merge once we've merged the other, related PRs

**Review by jackkoenig — CHANGES_REQUESTED** [review]
Because we're now so related in the 3.5 release process, we should instead deprecate in 3.5. Sorry for now helping this catch the train but we don't want 3.5.0 to slip any more.

**Comment by sequencer** [comment]
Sure. I'll deprecate it in 3.5

**Comment by sequencer** [comment]
Work on this in another PR.

**Pull request closed without merging**
