### PR TITLE
Publish website to branch

### PR DESCRIPTION
**Pull request by mwachs5**
### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [ ] Did you add at least one test demonstrating the PR?
- [ ] Did you delete any extraneous printlns/debugging code?
- [ ] Did you specify the type of improvement?
- [ ] Did you add appropriate documentation in `docs/src`?
- [ ] Did you state the API impact?
- [ ] Did you specify the code generation impact?
- [ ] Did you request a desired merge strategy?
- [ ] Did you add text to be included in the Release Notes for this change?

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (Bug fix: `3.4.x`, [small] API extension: `3.5.x`, API modification or big change: `3.6.0`)?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you do one of the following when ready to merge:
  - [ ] Squash: You/ the contributor `Enable auto-merge (squash)`, clean up the commit message, and label with `Please Merge`.
  - [ ] Merge: Ensure that contributor has cleaned up their commit history, then merge with `Create a merge commit`.

### CODE REVIEW

**Comment by jackkoenig** [comment]
@mwachs5 this is a PR against a branch so I'm guessing you don't want any review? Or what's the intent here?

**Comment by mwachs5** [comment]
the test is what happens when I merge to the website-branch, so I am gonna merge this, and then it should push to the gh-pages

**Comment by mwachs5** [comment]
Well, the automation worked to try, but it massively failed for some reason https://github.com/chipsalliance/chisel3/actions/runs/4009946484

**Comment by mwachs5** [comment]
Ok, the re-trigger passed but I guess because it was a manual trigger it did not work to push to the gh-pages branch https://github.com/chipsalliance/chisel3/actions/runs/4009946484/jobs/6886077173

**Pull request merged**
